# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [21]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [22]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Vertical stacking - Increasing the number of row
np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [24]:
# Checking the dimensions of the array
arr_3.ndim

2

In [25]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [27]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(0,10)

# Printing the created array
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [29]:
# Checking the rows and columns in the created array
arr_5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [31]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [32]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [33]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = arr_6.reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [34]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])